version: '3'
services:
  realtime:
    image: realtime/walrus
    build: .
    ports:
      - 4000:4000
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
      DB_SSL: "false"
      PORT: 4000
      JWT_SECRET: SOMETHING_SUPER_SECRET
      REPLICATION_MODE: RLS
      REPLICATION_POLL_INTERVAL: 100
      SECURE_CHANNELS: "true"
      SLOT_NAME: realtime_rls
      TEMPORARY_SLOT: "true"
    command: >
      bash -c "./prod/rel/realtime/bin/realtime eval Realtime.Release.migrate
      && ./prod/rel/realtime/bin/realtime start"
  db:
    image: supabase/postgres:13.3.0
    ports:
      - 5432:5432
    volumes:
      - ./dev/postgres/mnt:/docker-entrypoint-initdb.d/
    command:
      - postgres
      - -c
      - wal_level=logical
      - -c
      - max_slot_wal_keep_size=1024MB
    environment:
      POSTGRES_PASSWORD: postgres
