# docker-compose.yml

version: '3'
services:
  db:
    image: supabase/postgres:14.1.0.34
    ports:
      - "5432:5432"
    volumes:
    - ./dev/postgres/mnt:/docker-entrypoint-initdb.d/
    command:
    - postgres
    - -c
    - wal_level=logical
    environment: 
      POSTGRES_PASSWORD: postgres
  