name: Beacon Tests
defaults:
  run:
    shell: bash
    working-directory: ./beacon
on:
  pull_request:
    paths:
      - "beacon/**"

  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  MIX_ENV: test

jobs:
  tests:
    name: Tests & Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup elixir
        id: beam
        uses: erlef/setup-beam@v1
        with:
          otp-version: 27.x # Define the OTP version [required]
          elixir-version: 1.18.x # Define the elixir version [required]
      - name: Install dependencies
        run: mix deps.get
      - name: Start epmd
        run: epmd -daemon
      - name: Run tests
        run: MIX_ENV=test mix test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check for warnings
        run: mix compile --force --warnings-as-errors
      - name: Run format check
        run: mix format --check-formatted
