on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - 'main'

name: Default Checks

jobs:
  versions_updated:
    name: Versions Updated
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify Versions Updated
        uses: tj-actions/changed-files@v35
        id: verify_changed_files
        with:
          files: |
             mix.exs

      - name: Fail Unless Versions Updated
        id: fail_unless_changed
        if: steps.verify_changed_files.outputs.any_changed == 'false'
        run: |
              echo "::error ::Please update the mix.exs version"
              exit 1
